name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy na VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Instalar pnpm
        uses: pnpm/action-setup@v5

      - name: Instalar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Instalar dependências
        run: pnpm install
        #run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ${{ secrets.PROJECT_PATH }}
            git fetch origin main
            git reset --hard origin/main
            git clean -fxd -e .env
            cp .env .env.production
            /home/rhythmbot/.local/share/pnpm/pnpm install
            /home/rhythmbot/.local/share/pnpm/pnpm build
            sudo /usr/bin/cp files/rhythmbot.service /etc/systemd/system/rhythmbot.service
            sudo /usr/bin/systemctl daemon-reload
            sudo /usr/bin/systemctl restart rhythmbot
            
